name: Node.js CI for DEV

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  BUCKET_NAME: "doukan"
  AWS_REGION: "ap-southeast-1"

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # cache: 'yarn'
          # cache-dependency-path: "yarn.lock"
      - name: Install dependencies
        run: yarn
      - run: npm install eslint-plugin-import@latest --save-dev
      - run: yarn lint
      - run: yarn build

  S3PackageUpload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::552598673490:role/github-actions-oidc
          role-session-name: github-actions-oidc
          aws-region: ${{ env.AWS_REGION }}
      # Upload a file to AWS s3
      - name:  Copy index.js to s3
        run: |
          aws s3 cp dist/index.js s3://${{ env.BUCKET_NAME }}/

